# -*- coding: utf-8 -*-
"""candiadate elimation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1egpzRzkZyVaaWxn0tOUdG1mao0wpykwT
"""

import pandas as pd
import numpy as np

df = pd.read_csv('data.csv')

x_train = df.iloc[:,:6]
y_train = df.iloc[:,6:]

print(x_train)
print(y_train)

n_x_train = np.array(x_train)
n_y_train = np.array(y_train)

print(n_x_train)
print(n_y_train)

n_y_train[0][0]

def find_s(n_x_train,n_y_train):
    start = 0
    for i in range(len(n_x_train)):
        if n_y_train[i][0] == 'yes':
            s = n_x_train[0].copy()
            start = i
            break

    for i in range(start,len(n_x_train)):
        if n_y_train[i][0] == 'yes':
            for j in range(len(n_x_train[i])):
                if n_x_train[i][j] != s[j]:
                    s[j] = '?'

    return s

find_ans = find_s(n_x_train,n_y_train)
print(find_ans)

def candidate_elimination(x_train,y_train):
    start = 0
    for i in range(len(x_train)):
        if y_train[i][0] == 'yes':
            s = x_train[i].copy()
            start = i
            break
    gene = [["?" for _ in range(len(n_x_train[0]))] for _ in range(len(n_x_train))]

    for i in range(len(x_train)):
        if y_train[i][0] == 'yes':
            for j in range(len(x_train[i])):
                if x_train[i][j] != s[j]:
                    s[j] = "?"
        else:
            for j in range(len(x_train[i])):
                if x_train[i-1][j] == s[j]:
                    gene[i][j] = s[j]


    print(s)
    print(gene)

candidate_elimination(n_x_train,n_y_train)

